[package]
name = "spz_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.5.0"
lopdf = "0.32.0"
rayon = "1.9.0"
hex = "0.4.3"
rust-crypto = "0.2.0"
rand = "0.8.5"


